# yaml-language-server: disable
schema: "../../apps/backend/src/schema.gql"
documents: "src/**/*.{ts,tsx}"
overwrite: true
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"  
      - "typescript-react-apollo"
    config:
      withHooks: true
      withHOC: false
      withComponent: false
      scalars:
        DateTime: string
        JSON: any
      namingConvention:
        typeNames: pascal-case#pascalCase
      avoidOptionals:
        field: true
        inputValue: false
        object: false
        defaultValue: false