# Core configuration
variable "environment" {
  description = "Environment name (dev/prod)"
  type        = string
}

variable "project_name" {
  description = "Name of the project"
  type        = string
}

variable "aws_region" {
  description = "AWS region"
  type        = string
}

# SSH key is now auto-generated by EC2 module

# EC2 configuration
variable "instance_type" {
  description = "EC2 instance type"
  type        = string
}

variable "root_volume_size" {
  description = "Size of the root volume in GB"
  type        = number
}

variable "ssh_allowed_cidr_blocks" {
  description = "CIDR blocks allowed for SSH access"
  type        = list(string)
}

# API Gateway configuration
variable "enable_api_gateway" {
  description = "Whether to enable API Gateway for HTTPS termination"
  type        = bool
}

variable "backend_port" {
  description = "Port that the backend service runs on"
  type        = number
  default     = 4000
}

# ECR configuration
variable "backend_ecr_repository_url" {
  description = "ECR repository URL for backend image"
  type        = string
}

# Optional API Gateway custom domain configuration
variable "api_custom_domain_name" {
  description = "Custom domain name for API Gateway (optional)"
  type        = string
  default     = ""
}

variable "api_acm_certificate_arn" {
  description = "ACM certificate ARN for API Gateway custom domain (optional)"
  type        = string
  default     = ""
}

variable "api_route53_zone_id" {
  description = "Route53 hosted zone ID for API Gateway custom domain (optional)"
  type        = string
  default     = ""
}