version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    container_name: thclone-test-db
    environment:
      POSTGRES_DB: thclone_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5440:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d thclone_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test_db_data: