# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# Production environment
# Usage: docker compose -f docker-compose.prod.yml up

# Include core services (frontend excluded as it's served via S3 + CloudFront)
include:
  - services/postgres.yml
  - services/backend.yml
  - services/jaeger.yml
  - services/otel-collector.yml
