# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# Development environment (default)
# This file includes all individual service definitions and applies development-specific overrides
#
# Individual services are defined in ./services/ directory with their own documentation
# 
# Usage:
#   Development: docker compose up
#   Production:  docker compose -f docker-compose.prod.yml up
#   Test:        docker compose -f docker-compose.test.yml up

# Include all individual service definitions
include:
  - services/postgres.yml
  - services/backend.yml
  - services/frontend.yml
  - services/jaeger.yml
  - services/otel-collector.yml

# Development-specific overrides
services:
  postgres:
    environment:
      POSTGRES_DB: thclone_dev
      POSTGRES_USER: thclone
      POSTGRES_PASSWORD: thclone_password
    ports:
      - "5433:5432"  # Non-standard port to avoid conflicts

  backend:
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://thclone:thclone_password@postgres:5432/thclone_dev
      JWT_SECRET: your-super-secret-jwt-key-here
      FRONTEND_URL: http://localhost:3000
    volumes:
      # Mount source code for hot-reloading
      - ../apps/backend:/app/apps/backend
      - ../packages:/app/packages
      - /app/node_modules
      - /app/apps/backend/node_modules
    command: ["yarn", "workspace", "@thclone/backend", "dev"]

  frontend:
    environment:
      VITE_GRAPHQL_URL: http://localhost:4000/graphql
    ports:
      - "3000:8080"
    volumes:
      # Mount source code for hot-reloading
      - ../apps/frontend:/app/apps/frontend
      - ../packages:/app/packages
      - /app/node_modules
      - /app/apps/frontend/node_modules
    command: ["yarn", "workspace", "@thclone/frontend", "dev", "--host", "0.0.0.0", "--port", "3000"]

networks:
  default:
    name: thclone-network