version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: thclone-postgres
    environment:
      POSTGRES_DB: thclone_dev
      POSTGRES_USER: thclone
      POSTGRES_PASSWORD: thclone_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thclone -d thclone_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: thclone-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: thclone-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://thclone:thclone_password@postgres:5432/thclone_dev
      JWT_SECRET: your-super-secret-jwt-key-here
      REDIS_URL: redis://redis:6379
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../apps/backend:/app/apps/backend
      - ../packages:/app/packages
      - /app/node_modules
      - /app/apps/backend/node_modules
    command: ["yarn", "workspace", "@thclone/backend", "dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: thclone-frontend
    environment:
      VITE_GRAPHQL_URL: http://localhost:4000/graphql
    ports:
      - "3000:8080"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ../apps/frontend:/app/apps/frontend
      - ../packages:/app/packages
      - /app/node_modules
      - /app/apps/frontend/node_modules
    command: ["yarn", "workspace", "@thclone/frontend", "dev", "--host", "0.0.0.0", "--port", "3000"]

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: thclone-network